### ISSUE TITLE
Make scientificname table

### ISSUE THREAD

**Issue by damianooldoni** [inbo/speciesbim#1]
A table with following fields:

- `id`: primary key
- `taxonId`: foreign key pointing to `taxonomy`
- ` scientificName` : char  e.g. _Vulpes vulpes_
- `authorship`: char e.g. _(Linnaeus, 1758)_
- `lastCheckDate`: datetime e.g. 2020-05-27 11:24:00
In case rank and/or kingdom will improve the match to GBIF Backbone we could consider to add it, but better not doing it.

This table has to be populated with the used taxa from `biodiv.taxon`. SQL query to find them:
`tabletaxon_sql = 'select id, acceptedname, scientificnameauthorship, taxonranken from biodiv.taxon where ' \`
`  'id in (select nptaxonid from biodiv.commontaxa) or ' \`
`  'id in (select taxonid from biodiv.speciesannex) or ' \`
`  'id in (select taxonid from biodiv.media) or ' \`
`  'id in (select taxonid from biodiv.identifiablespecies where ' \`
`  'id in (select identifiablespeciesid from biodiv.occurence))'`

**Comment by niconoe** [comment]
I suggest using `taxonomyid` the FK to the `taxonomy` table, so we match their current naming scheme and we avoid confusion between the old `taxon` and the new `taxonomy` table.

I was also wondering if we should create a (temporary)  FK to the current `taxon` table. It would be for traceability reasons only: we populate it when adding data to this table to know where (in `taxon`) this initial data comes from (and be able to retrieve any other linked data if needed), and would drop the FK at the end of the project (at the time we also drop the `taxon` table, because we are confident it's now fully replaced).

Does that make any sense?

**Comment by niconoe** [comment]
I think I would also use `lastCheck` or `lastMatch` (maybe more explicit?), especially is the stored value is not a Date, but a Datetime.

**Comment by niconoe** [comment]
Update: running the new `transform_db.py` script (see #3), now creates and populates that table.

**Comment by peterdesmet** [comment]
- Agree: `taxonomyID` is better
- Yes, we could keep a temporary `deprecatedTaxonID`
- I would name the date field as `lastMatched`

**Comment by niconoe** [comment]
Updated according to @peterdesmet remarks.

**Comment by niconoe** [comment]
The basic structure of the table being there, I suggest closing this issue and opening new ones for more specific changes (easier to follow the discussion). Objections?

**Comment by damianooldoni** [comment]
Agree.
