### ISSUE TITLE
Need of rankId and rank table instead of just string for ranks

### ISSUE THREAD

**Issue by damianooldoni** [inbo/speciesbim#20]

**Comment by peterdesmet** [comment]
Advantage would be to that `taxonomy` table is self contained and populated from GBIF.

**Comment by niconoe** [comment]
I'd argue it's a plus in its current form, for the following reasons:

- We're populating a relational database, and it fits better the relational model (therefore it will be more simple and performant to actually use/query the data later - the "flat" solution is only simpler if you consider only the create/import stage and not the whole data lifecycle) => I already faced this while writing the sample SQL views in `README.md`
- In its current implementation, it is also dynamically populated by the script based on returned GBIF data. So in practice, the `rank` table has the same practical properties (can be dropped and recreated anytime without the need of non-GBIF data) than the `taxonomy` table, the only difference is that they are two tables instead of one (but I think it's quite normal to have a few more tables in the actual implementation than in the initially imagined solution, which is always a bit naïve)

**Comment by damianooldoni** [comment]
We can close this after meeting of today. Storing ranks in a table is ok for BIM as well.
